import { CharDefinition } from './definitions.js';

export default [
    { name: 'Null', char: null },
    { name: 'Start of Heading', char: null },
    { name: 'Start of Text', char: null },
    { name: 'End of Text', char: null },
    { name: 'End of Transmission', char: null },
    { name: 'Enquiry', char: null },
    { name: 'Acknowledge', char: null },
    { name: 'Bell', char: null },
    { name: 'Backspace', char: null },
    { name: 'Horizontal Tabulation', char: null },
    { name: 'Line Feed', char: null },
    { name: 'Vertical Tabulation', char: null },
    { name: 'Form Feed', char: null },
    { name: 'Carriage Return', char: null },
    { name: 'Shift Out', char: null },
    { name: 'Shift In', char: null },
    { name: 'Data Link Escape', char: null },
    { name: 'Device Control 1', char: null },
    { name: 'Device Control 2', char: null },
    { name: 'Device Control 3', char: null },
    { name: 'Device Control 4', char: null },
    { name: 'Negative Acknowledge', char: null },
    { name: 'Synchronous Idle', char: null },
    { name: 'End of Transmission Block', char: null },
    { name: 'Cancel', char: null },
    { name: 'End of Medium', char: null },
    { name: 'Substitute', char: null },
    { name: 'Escape', char: null },
    { name: 'File Separator', char: null },
    { name: 'Group Separator', char: null },
    { name: 'Record Separator', char: null },
    { name: 'Unit Separator', char: null },
    { name: 'Space', char: ' ' },
    { name: 'Exclamation Point', char: '!' },
    { name: 'Quotation Marks (Diaeresis)', char: '"' },
    { name: 'Number Sign', char: '#' },
    { name: 'Dollar Sign', char: '$' },
    { name: 'Percent Sign', char: '%' },
    { name: 'Ampersand', char: '&' },
    { name: 'Apostrophe', char: "'" },
    { name: 'Opening Parenthesis', char: '(' },
    { name: 'Closing Parenthesis', char: ')' },
    { name: 'Asterisk', char: '*' },
    { name: 'Plus', char: '+' },
    { name: 'Comma (Cedilla)', char: ',' },
    { name: 'Hyphen (Minus)', char: '-' },
    { name: 'Period (Decimal Point)', char: '.' },
    { name: 'Slant', char: '/' },
    { name: 'Digit 0', char: '0' },
    { name: 'Digit 1', char: '1' },
    { name: 'Digit 2', char: '2' },
    { name: 'Digit 3', char: '3' },
    { name: 'Digit 4', char: '4' },
    { name: 'Digit 5', char: '5' },
    { name: 'Digit 6', char: '6' },
    { name: 'Digit 7', char: '7' },
    { name: 'Digit 8', char: '8' },
    { name: 'Digit 9', char: '9' },
    { name: 'Colon', char: ':' },
    { name: 'Semicolon', char: ';' },
    { name: 'Less Than', char: '<' },
    { name: 'Equals', char: '=' },
    { name: 'Greater Than', char: '>' },
    { name: 'Question Mark', char: '?' },
    { name: 'Commercial At', char: '@' },
    { name: 'Uppercase A', char: 'A' },
    { name: 'Uppercase B', char: 'B' },
    { name: 'Uppercase C', char: 'C' },
    { name: 'Uppercase D', char: 'D' },
    { name: 'Uppercase E', char: 'E' },
    { name: 'Uppercase F', char: 'F' },
    { name: 'Uppercase G', char: 'G' },
    { name: 'Uppercase H', char: 'H' },
    { name: 'Uppercase I', char: 'I' },
    { name: 'Uppercase J', char: 'J' },
    { name: 'Uppercase K', char: 'K' },
    { name: 'Uppercase L', char: 'L' },
    { name: 'Uppercase M', char: 'M' },
    { name: 'Uppercase N', char: 'N' },
    { name: 'Uppercase O', char: 'O' },
    { name: 'Uppercase P', char: 'P' },
    { name: 'Uppercase Q', char: 'Q' },
    { name: 'Uppercase R', char: 'R' },
    { name: 'Uppercase S', char: 'S' },
    { name: 'Uppercase T', char: 'T' },
    { name: 'Uppercase U', char: 'U' },
    { name: 'Uppercase V', char: 'V' },
    { name: 'Uppercase W', char: 'W' },
    { name: 'Uppercase X', char: 'X' },
    { name: 'Uppercase Y', char: 'Y' },
    { name: 'Uppercase Z', char: 'Z' },
    { name: 'Opening Bracket', char: '[' },
    { name: 'Reverse Slant', char: '\\' },
    { name: 'Closing Bracket', char: ']' },
    { name: 'Circumflex', char: '^' },
    { name: 'Underline', char: '_' },
    { name: 'Grave Accent', char: '`' },
    { name: 'Lowercase A', char: 'a' },
    { name: 'Lowercase B', char: 'b' },
    { name: 'Lowercase C', char: 'c' },
    { name: 'Lowercase D', char: 'd' },
    { name: 'Lowercase E', char: 'e' },
    { name: 'Lowercase F', char: 'f' },
    { name: 'Lowercase G', char: 'g' },
    { name: 'Lowercase H', char: 'h' },
    { name: 'Lowercase I', char: 'i' },
    { name: 'Lowercase J', char: 'j' },
    { name: 'Lowercase K', char: 'k' },
    { name: 'Lowercase L', char: 'l' },
    { name: 'Lowercase M', char: 'm' },
    { name: 'Lowercase N', char: 'n' },
    { name: 'Lowercase O', char: 'o' },
    { name: 'Lowercase P', char: 'p' },
    { name: 'Lowercase Q', char: 'q' },
    { name: 'Lowercase R', char: 'r' },
    { name: 'Lowercase S', char: 's' },
    { name: 'Lowercase T', char: 't' },
    { name: 'Lowercase U', char: 'u' },
    { name: 'Lowercase V', char: 'v' },
    { name: 'Lowercase W', char: 'w' },
    { name: 'Lowercase X', char: 'x' },
    { name: 'Lowercase Y', char: 'y' },
    { name: 'Lowercase Z', char: 'z' },
    { name: 'Opening Brace', char: '{' },
    { name: 'Vertical Line', char: '|' },
    { name: 'Closing Brace', char: '}' },
    { name: 'Tilde', char: '~' },
    { name: 'Delete', char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
] as CharDefinition[];
