export default [
    { name: 'Null', char: null },
    { name: 'Start of Heading', char: null },
    { name: 'Start of Text', char: null },
    { name: 'End of Text', char: null },
    { name: 'End of Transmission', char: null },
    { name: 'Enquiry', char: null },
    { name: 'Acknowledge', char: null },
    { name: 'Bell', char: null },
    { name: 'Backspace', char: null },
    { name: 'Horizontal Tabulation', char: null },
    { name: 'Line Feed', char: null },
    { name: 'Vertical Tabulation', char: null },
    { name: 'Form Feed', char: null },
    { name: 'Carriage Return', char: null },
    { name: 'Shift Out', char: null },
    { name: 'Shift In', char: null },
    { name: 'Data Link Escape', char: null },
    { name: 'Device Control 1', char: null },
    { name: 'Device Control 2', char: null },
    { name: 'Device Control 3', char: null },
    { name: 'Device Control 4', char: null },
    { name: 'Negative Acknowledge', char: null },
    { name: 'Synchronous Idle', char: null },
    { name: 'End of Transmission Block', char: null },
    { name: 'Cancel', char: null },
    { name: 'End of Medium', char: null },
    { name: 'Substitute', char: null },
    { name: 'Escape', char: null },
    { name: 'File Separator', char: null },
    { name: 'Group Separator', char: null },
    { name: 'Record Separator', char: null },
    { name: 'Unit Separator', char: null },
    { name: 'Space', char: ' ' },
    { name: 'Exclamation Point', char: '!' },
    { name: 'Quotation Marks (Diaeresis)', char: '"' },
    { name: 'Number Sign', char: '#' },
    { name: 'Dollar Sign', char: '$' },
    { name: 'Percent Sign', char: '%' },
    { name: 'Ampersand', char: '&' },
    { name: 'Apostrophe', char: "'" },
    { name: 'Opening Parenthesis', char: '(' },
    { name: 'Closing Parenthesis', char: ')' },
    { name: 'Asterisk', char: '*' },
    { name: 'Plus', char: '+' },
    { name: 'Comma (Cedilla)', char: ',' },
    { name: 'Hyphen (Minus)', char: '-' },
    { name: 'Period (Decimal Point)', char: '.' },
    { name: 'Slant', char: '/' },
    { name: 'Digit 0', char: '0' },
    { name: 'Digit 1', char: '1' },
    { name: 'Digit 2', char: '2' },
    { name: 'Digit 3', char: '3' },
    { name: 'Digit 4', char: '4' },
    { name: 'Digit 5', char: '5' },
    { name: 'Digit 6', char: '6' },
    { name: 'Digit 7', char: '7' },
    { name: 'Digit 8', char: '8' },
    { name: 'Digit 9', char: '9' },
    { name: 'Colon', char: ':' },
    { name: 'Semicolon', char: ';' },
    { name: 'Less Than', char: '<' },
    { name: 'Equals', char: '=' },
    { name: 'Greater Than', char: '>' },
    { name: 'Question Mark', char: '?' },
    { name: 'Commercial At', char: '@' },
    { name: 'Uppercase A', char: 'A' },
    { name: 'Uppercase B', char: 'B' },
    { name: 'Uppercase C', char: 'C' },
    { name: 'Uppercase D', char: 'D' },
    { name: 'Uppercase E', char: 'E' },
    { name: 'Uppercase F', char: 'F' },
    { name: 'Uppercase G', char: 'G' },
    { name: 'Uppercase H', char: 'H' },
    { name: 'Uppercase I', char: 'I' },
    { name: 'Uppercase J', char: 'J' },
    { name: 'Uppercase K', char: 'K' },
    { name: 'Uppercase L', char: 'L' },
    { name: 'Uppercase M', char: 'M' },
    { name: 'Uppercase N', char: 'N' },
    { name: 'Uppercase O', char: 'O' },
    { name: 'Uppercase P', char: 'P' },
    { name: 'Uppercase Q', char: 'Q' },
    { name: 'Uppercase R', char: 'R' },
    { name: 'Uppercase S', char: 'S' },
    { name: 'Uppercase T', char: 'T' },
    { name: 'Uppercase U', char: 'U' },
    { name: 'Uppercase V', char: 'V' },
    { name: 'Uppercase W', char: 'W' },
    { name: 'Uppercase X', char: 'X' },
    { name: 'Uppercase Y', char: 'Y' },
    { name: 'Uppercase Z', char: 'Z' },
    { name: 'Opening Bracket', char: '[' },
    { name: 'Reverse Slant', char: '\\' },
    { name: 'Closing Bracket', char: ']' },
    { name: 'Circumflex', char: '^' },
    { name: 'Underline', char: '_' },
    { name: 'Grave Accent', char: '`' },
    { name: 'Lowercase A', char: 'a' },
    { name: 'Lowercase B', char: 'b' },
    { name: 'Lowercase C', char: 'c' },
    { name: 'Lowercase D', char: 'd' },
    { name: 'Lowercase E', char: 'e' },
    { name: 'Lowercase F', char: 'f' },
    { name: 'Lowercase G', char: 'g' },
    { name: 'Lowercase H', char: 'h' },
    { name: 'Lowercase I', char: 'i' },
    { name: 'Lowercase J', char: 'j' },
    { name: 'Lowercase K', char: 'k' },
    { name: 'Lowercase L', char: 'l' },
    { name: 'Lowercase M', char: 'm' },
    { name: 'Lowercase N', char: 'n' },
    { name: 'Lowercase O', char: 'o' },
    { name: 'Lowercase P', char: 'p' },
    { name: 'Lowercase Q', char: 'q' },
    { name: 'Lowercase R', char: 'r' },
    { name: 'Lowercase S', char: 's' },
    { name: 'Lowercase T', char: 't' },
    { name: 'Lowercase U', char: 'u' },
    { name: 'Lowercase V', char: 'v' },
    { name: 'Lowercase W', char: 'w' },
    { name: 'Lowercase X', char: 'x' },
    { name: 'Lowercase Y', char: 'y' },
    { name: 'Lowercase Z', char: 'z' },
    { name: 'Opening Brace', char: '{' },
    { name: 'Vertical Line', char: '|' },
    { name: 'Closing Brace', char: '}' },
    { name: 'Tilde', char: '~' },
    { name: 'Delete', char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: null, char: null },
    { name: 'No-Break Space', char: ' ' },
    { name: 'Inverted Exclamation Mark', char: '¡' },
    { name: 'Cent Sign', char: '¢' },
    { name: 'Pound Sign', char: '£' },
    { name: 'Currency Sign', char: '¤' },
    { name: 'Yen Sign', char: '¥' },
    { name: 'Broken Bar', char: '¦' },
    { name: 'Section Sign', char: '§' },
    { name: 'Diaeresis', char: '¨' },
    { name: 'Copyright Sign', char: '©' },
    { name: 'Feminine Ordinal Indicator', char: 'ª' },
    { name: 'Left-Pointing Double Angle Quotation Mark', char: '«' },
    { name: 'Not Sign', char: '¬' },
    { name: 'Soft Hyphen', char: '­' },
    { name: 'Registered Sign', char: '®' },
    { name: 'Macron', char: '¯' },
    { name: 'Degree Sign', char: '°' },
    { name: 'Plus-Minus Sign', char: '±' },
    { name: 'Superscript Two', char: '²' },
    { name: 'Superscript Three', char: '³' },
    { name: 'Acute Accent', char: '´' },
    { name: 'Micro Sign', char: 'µ' },
    { name: 'Pilcrow Sign', char: '¶' },
    { name: 'Middle Dot', char: '·' },
    { name: 'Cedilla', char: '¸' },
    { name: 'Superscript One', char: '¹' },
    { name: 'Masculine Ordinal Indicator', char: 'º' },
    { name: 'Right-Pointing Double Angle Quotation Mark', char: '»' },
    { name: 'Vulgar Fraction One Quarter', char: '¼' },
    { name: 'Vulgar Fraction One Half', char: '½' },
    { name: 'Vulgar Fraction Three Quarters', char: '¾' },
    { name: 'Inverted Question Mark', char: '¿' },
    { name: 'Uppercase A With Grave', char: 'À' },
    { name: 'Uppercase A With Acute', char: 'Á' },
    { name: 'Uppercase A With Circumflex', char: 'Â' },
    { name: 'Uppercase A With Tilde', char: 'Ã' },
    { name: 'Uppercase A With Diaeresis', char: 'Ä' },
    { name: 'Uppercase A With Ring Above', char: 'Å' },
    { name: 'Uppercase AE', char: 'Æ' },
    { name: 'Uppercase C With Cedilla', char: 'Ç' },
    { name: 'Uppercase E With Grave', char: 'È' },
    { name: 'Uppercase E With Acute', char: 'É' },
    { name: 'Uppercase E With Circumflex', char: 'Ê' },
    { name: 'Uppercase E With Diaeresis', char: 'Ë' },
    { name: 'Uppercase I With Grave', char: 'Ì' },
    { name: 'Uppercase I With Acute', char: 'Í' },
    { name: 'Uppercase I With Circumflex', char: 'Î' },
    { name: 'Uppercase I With Diaeresis', char: 'Ï' },
    { name: 'Uppercase Eth', char: 'Ð' },
    { name: 'Uppercase N With Tilde', char: 'Ñ' },
    { name: 'Uppercase O With Grave', char: 'Ò' },
    { name: 'Uppercase O With Acute', char: 'Ó' },
    { name: 'Uppercase O With Circumflex', char: 'Ô' },
    { name: 'Uppercase O With Tilde', char: 'Õ' },
    { name: 'Uppercase O With Diaeresis', char: 'Ö' },
    { name: 'Multiplication Sign', char: '×' },
    { name: 'Uppercase O With Stroke', char: 'Ø' },
    { name: 'Uppercase U With Grave', char: 'Ù' },
    { name: 'Uppercase U With Acute', char: 'Ú' },
    { name: 'Uppercase U With Circumflex', char: 'Û' },
    { name: 'Uppercase U With Diaeresis', char: 'Ü' },
    { name: 'Uppercase Y With Acute', char: 'Ý' },
    { name: 'Uppercase Thorn', char: 'Þ' },
    { name: 'Lowercase Sharp S', char: 'ß' },
    { name: 'Lowercase A With Grave', char: 'à' },
    { name: 'Lowercase A With Acute', char: 'á' },
    { name: 'Lowercase A With Circumflex', char: 'â' },
    { name: 'Lowercase A With Tilde', char: 'ã' },
    { name: 'Lowercase A With Diaeresis', char: 'ä' },
    { name: 'Lowercase A With Ring Above', char: 'å' },
    { name: 'Lowercase AE', char: 'æ' },
    { name: 'Lowercase C With Cedilla', char: 'ç' },
    { name: 'Lowercase E With Grave', char: 'è' },
    { name: 'Lowercase E With Acute', char: 'é' },
    { name: 'Lowercase E With Circumflex', char: 'ê' },
    { name: 'Lowercase E With Diaeresis', char: 'ë' },
    { name: 'Lowercase I With Grave', char: 'ì' },
    { name: 'Lowercase I With Acute', char: 'í' },
    { name: 'Lowercase I With Circumflex', char: 'î' },
    { name: 'Lowercase I With Diaeresis', char: 'ï' },
    { name: 'Lowercase Eth', char: 'ð' },
    { name: 'Lowercase N With Tilde', char: 'ñ' },
    { name: 'Lowercase O With Grave', char: 'ò' },
    { name: 'Lowercase O With Acute', char: 'ó' },
    { name: 'Lowercase O With Circumflex', char: 'ô' },
    { name: 'Lowercase O With Tilde', char: 'õ' },
    { name: 'Lowercase O With Diaeresis', char: 'ö' },
    { name: 'Division Sign', char: '÷' },
    { name: 'Lowercase O With Stroke', char: 'ø' },
    { name: 'Lowercase U With Grave', char: 'ù' },
    { name: 'Lowercase U With Acute', char: 'ú' },
    { name: 'Lowercase U With Circumflex', char: 'û' },
    { name: 'Lowercase U With Diaeresis', char: 'ü' },
    { name: 'Lowercase Y With Acute', char: 'ý' },
    { name: 'Lowercase Thorn', char: 'þ' },
    { name: 'Lowercase Y With Diaeresis', char: 'ÿ' },
];
//# sourceMappingURL=iso8859_1.js.map