export default [
    'Null',
    'Start of Heading',
    'Start of Text',
    'End of Text',
    'End of Transmission',
    'Enquiry',
    'Acknowledge',
    'Bell',
    'Backspace',
    'Horizontal Tabulation',
    'Line Feed',
    'Vertical Tabulation',
    'Form Feed',
    'Carriage Return',
    'Shift Out',
    'Shift In',
    'Data Link Escape',
    'Device Control 1',
    'Device Control 2',
    'Device Control 3',
    'Device Control 4',
    'Negative Acknowledge',
    'Synchronous Idle',
    'End of Transmission Block',
    'Cancel',
    'End of Medium',
    'Substitute',
    'Escape',
    'File Separator',
    'Group Separator',
    'Record Separator',
    'Unit Separator',
    'Space',
    'Exclamation Point',
    'Quotation Marks (Diaeresis)',
    'Number Sign',
    'Dollar Sign',
    'Percent Sign',
    'Ampersand',
    'Apostrophe',
    'Opening Parenthesis',
    'Closing Parenthesis',
    'Asterisk',
    'Plus',
    'Comma (Cedilla)',
    'Hyphen (Minus)',
    'Period (Decimal Point)',
    'Slant',
    'Digit 0',
    'Digit 1',
    'Digit 2',
    'Digit 3',
    'Digit 4',
    'Digit 5',
    'Digit 6',
    'Digit 7',
    'Digit 8',
    'Digit 9',
    'Colon',
    'Semicolon',
    'Less Than',
    'Equals',
    'Greater Than',
    'Question Mark',
    'Commercial At',
    'Uppercase A',
    'Uppercase B',
    'Uppercase C',
    'Uppercase D',
    'Uppercase E',
    'Uppercase F',
    'Uppercase G',
    'Uppercase H',
    'Uppercase I',
    'Uppercase J',
    'Uppercase K',
    'Uppercase L',
    'Uppercase M',
    'Uppercase N',
    'Uppercase O',
    'Uppercase P',
    'Uppercase Q',
    'Uppercase R',
    'Uppercase S',
    'Uppercase T',
    'Uppercase U',
    'Uppercase V',
    'Uppercase W',
    'Uppercase X',
    'Uppercase Y',
    'Uppercase Z',
    'Opening Bracket',
    'Reverse Slant',
    'Closing Bracket',
    'Circumflex',
    'Underline',
    'Grave Accent',
    'Lowercase A',
    'Lowercase B',
    'Lowercase C',
    'Lowercase D',
    'Lowercase E',
    'Lowercase F',
    'Lowercase G',
    'Lowercase H',
    'Lowercase I',
    'Lowercase J',
    'Lowercase K',
    'Lowercase L',
    'Lowercase M',
    'Lowercase N',
    'Lowercase O',
    'Lowercase P',
    'Lowercase Q',
    'Lowercase R',
    'Lowercase S',
    'Lowercase T',
    'Lowercase U',
    'Lowercase V',
    'Lowercase W',
    'Lowercase X',
    'Lowercase Y',
    'Lowercase Z',
    'Opening Brace',
    'Vertical Line',
    'Closing Brace',
    'Tilde',
    'Delete',
];
//# sourceMappingURL=ascii.js.map