import ascii from './ascii.js';
export default [
    ...ascii,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    'No-Break Space',
    'Inverted Exclamation Mark',
    'Cent Sign',
    'Pound Sign',
    'Currency Sign',
    'Yen Sign',
    'Broken Bar',
    'Section Sign',
    'Diaeresis',
    'Copyright Sign',
    'Feminine Ordinal Indicator',
    'Left-Pointing Double Angle Quotation Mark',
    'Not Sign',
    'Soft Hyphen',
    'Registered Sign',
    'Macron',
    'Degree Sign',
    'Plus-Minus Sign',
    'Superscript Two',
    'Superscript Three',
    'Acute Accent',
    'Micro Sign',
    'Pilcrow Sign',
    'Middle Dot',
    'Cedilla',
    'Superscript One',
    'Masculine Ordinal Indicator',
    'Right-Pointing Double Angle Quotation Mark',
    'Vulgar Fraction One Quarter',
    'Vulgar Fraction One Half',
    'Vulgar Fraction Three Quarters',
    'Inverted Question Mark',
    'Uppercase A With Grave',
    'Uppercase A With Acute',
    'Uppercase A With Circumflex',
    'Uppercase A With Tilde',
    'Uppercase A With Diaeresis',
    'Uppercase A With Ring Above',
    'Uppercase AE',
    'Uppercase C With Cedilla',
    'Uppercase E With Grave',
    'Uppercase E With Acute',
    'Uppercase E With Circumflex',
    'Uppercase E With Diaeresis',
    'Uppercase I With Grave',
    'Uppercase I With Acute',
    'Uppercase I With Circumflex',
    'Uppercase I With Diaeresis',
    'Uppercase Eth',
    'Uppercase N With Tilde',
    'Uppercase O With Grave',
    'Uppercase O With Acute',
    'Uppercase O With Circumflex',
    'Uppercase O With Tilde',
    'Uppercase O With Diaeresis',
    'Multiplication Sign',
    'Uppercase O With Stroke',
    'Uppercase U With Grave',
    'Uppercase U With Acute',
    'Uppercase U With Circumflex',
    'Uppercase U With Diaeresis',
    'Uppercase Y With Acute',
    'Uppercase Thorn',
    'Lowercase Sharp S',
    'Lowercase A With Grave',
    'Lowercase A With Acute',
    'Lowercase A With Circumflex',
    'Lowercase A With Tilde',
    'Lowercase A With Diaeresis',
    'Lowercase A With Ring Above',
    'Lowercase AE',
    'Lowercase C With Cedilla',
    'Lowercase E With Grave',
    'Lowercase E With Acute',
    'Lowercase E With Circumflex',
    'Lowercase E With Diaeresis',
    'Lowercase I With Grave',
    'Lowercase I With Acute',
    'Lowercase I With Circumflex',
    'Lowercase I With Diaeresis',
    'Lowercase Eth',
    'Lowercase N With Tilde',
    'Lowercase O With Grave',
    'Lowercase O With Acute',
    'Lowercase O With Circumflex',
    'Lowercase O With Tilde',
    'Lowercase O With Diaeresis',
    'Division Sign',
    'Lowercase O With Stroke',
    'Lowercase U With Grave',
    'Lowercase U With Acute',
    'Lowercase U With Circumflex',
    'Lowercase U With Diaeresis',
    'Lowercase Y With Acute',
    'Lowercase Thorn',
    'Lowercase Y With Diaeresis',
];
//# sourceMappingURL=iso8859_1.js.map