const controlCharacters = [
    'Null',
    'Start of Heading',
    'Start of Text',
    'End of Text',
    'End of Transmission',
    'Enquiry',
    'Acknowledge',
    'Bell',
    'Backspace',
    'Horizontal Tabulation',
    'Line Feed',
    'Vertical Tabulation',
    'Form Feed',
    'Carriage Return',
    'Shift Out',
    'Shift In',
    'Data Link Escape',
    'Device Control 1',
    'Device Control 2',
    'Device Control 3',
    'Device Control 4',
    'Negative Acknowledge',
    'Synchronous Idle',
    'End of Transmission Block',
    'Cancel',
    'End of Medium',
    'Substitute',
    'Escape',
    'File Separator',
    'Group Separator',
    'Record Separator',
    'Unit Separator',
];
const ascii = [
    ...controlCharacters,
    'Space',
    'Exclamation Point',
    'Quotation Marks (Diaeresis)',
    'Number Sign',
    'Dollar Sign',
    'Percent Sign',
    'Ampersand',
    'Apostrophe',
    'Opening Parenthesis',
    'Closing Parenthesis',
    'Asterisk',
    'Plus',
    'Comma (Cedilla)',
    'Hyphen (Minus)',
    'Period (Decimal Point)',
    'Slant',
    'Digit 0',
    'Digit 1',
    'Digit 2',
    'Digit 3',
    'Digit 4',
    'Digit 5',
    'Digit 6',
    'Digit 7',
    'Digit 8',
    'Digit 9',
    'Colon',
    'Semicolon',
    'Less Than',
    'Equals',
    'Greater Than',
    'Question Mark',
    'Commercial At',
    'Uppercase A',
    'Uppercase B',
    'Uppercase C',
    'Uppercase D',
    'Uppercase E',
    'Uppercase F',
    'Uppercase G',
    'Uppercase H',
    'Uppercase I',
    'Uppercase J',
    'Uppercase K',
    'Uppercase L',
    'Uppercase M',
    'Uppercase N',
    'Uppercase O',
    'Uppercase P',
    'Uppercase Q',
    'Uppercase R',
    'Uppercase S',
    'Uppercase T',
    'Uppercase U',
    'Uppercase V',
    'Uppercase W',
    'Uppercase X',
    'Uppercase Y',
    'Uppercase Z',
    'Opening Bracket',
    'Reverse Slant',
    'Closing Bracket',
    'Circumflex',
    'Underline',
    'Grave Accent',
    'Lowercase A',
    'Lowercase B',
    'Lowercase C',
    'Lowercase D',
    'Lowercase E',
    'Lowercase F',
    'Lowercase G',
    'Lowercase H',
    'Lowercase I',
    'Lowercase J',
    'Lowercase K',
    'Lowercase L',
    'Lowercase M',
    'Lowercase N',
    'Lowercase O',
    'Lowercase P',
    'Lowercase Q',
    'Lowercase R',
    'Lowercase S',
    'Lowercase T',
    'Lowercase U',
    'Lowercase V',
    'Lowercase W',
    'Lowercase X',
    'Lowercase Y',
    'Lowercase Z',
    'Opening Brace',
    'Vertical Line',
    'Closing Brace',
    'Tilde',
    'Delete',
];
// @ts-ignore
const iso8859_1 = [
    ...ascii,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    'No-Break Space',
    'Inverted Exclamation Mark',
    'Cent Sign',
    'Pound Sign',
    'Currency Sign',
    'Yen Sign',
    'Broken Bar',
    'Section Sign',
    'Diaeresis',
    'Copyright Sign',
    'Feminine Ordinal Indicator',
    'Left-Pointing Double Angle Quotation Mark',
    'Not Sign',
    'Soft Hyphen',
    'Registered Sign',
    'Macron',
    'Degree Sign',
    'Plus-Minus Sign',
    'Superscript Two',
    'Superscript Three',
    'Acute Accent',
    'Micro Sign',
    'Pilcrow Sign',
    'Middle Dot',
    'Cedilla',
    'Superscript One',
    'Masculine Ordinal Indicator',
    'Right-Pointing Double Angle Quotation Mark',
    'Vulgar Fraction One Quarter',
    'Vulgar Fraction One Half',
    'Vulgar Fraction Three Quarters',
    'Inverted Question Mark',
    'Uppercase A With Grave',
    'Uppercase A With Acute',
    'Uppercase A With Circumflex',
    'Uppercase A With Tilde',
    'Uppercase A With Diaeresis',
    'Uppercase A With Ring Above',
    'Uppercase AE',
    'Uppercase C With Cedilla',
    'Uppercase E With Grave',
    'Uppercase E With Acute',
    'Uppercase E With Circumflex',
    'Uppercase E With Diaeresis',
    'Uppercase I With Grave',
    'Uppercase I With Acute',
    'Uppercase I With Circumflex',
    'Uppercase | With Diaeresis',
    'Uppercase Eth',
    'Uppercase N With Tilde',
    'Uppercase O With Grave',
    'Uppercase O With Acute',
    'Uppercase O With Circumflex',
    'Uppercase O With Tilde',
    'Uppercase O With Diaeresis',
    'Multiplication Sign',
    'Uppercase O With Stroke',
    'Uppercase U With Grave',
    'Uppercase U With Acute',
    'Uppercase U With Circumflex',
    'Uppercase U With Diaeresis',
    'Uppercase Y With Acute',
    'Uppercase Thorn',
    'Lowercase Sharp S',
    'Lowercase A With Grave',
    'Lowercase A With Acute',
    'Lowercase A With Circumflex',
    'Lowercase A With Tilde',
    'Lowercase A With Diaeresis',
    'Lowercase A With Ring Above',
    'Lowercase AE',
    'Lowercase C With Cedilla',
    'Lowercase E With Grave',
    'Lowercase E With Acute',
    'Lowercase E With Circumflex',
    'Lowercase E With Diaeresis',
    'Lowercase I With Grave',
    'Lowercase I With Acute',
    'Lowercase I With Circumflex',
    'Lowercase I With Diaeresis',
    'Lowercase Eth',
    'Lowercase N With Tilde',
    'Lowercase O With Grave',
    'Lowercase O With Acute',
    'Lowercase O With Circumflex',
    'Lowercase O With Tilde',
    'Lowercase O With Diaeresis',
    'Division Sign',
    'Lowercase O With Stroke',
    'Lowercase U With Grave',
    'Lowercase U With Acute',
    'Lowercase U With Circumflex',
    'Lowercase U With Diaeresis',
    'Lowercase Y With Acute',
    'Lowercase Thorn',
    'Lowercase Y With Diaeresis',
];
// @ts-ignore
const windows1252 = [
    ...ascii,
    'Euro Sign',
    null,
    'Single Low-9 Quotation Mark',
    'Lowercase F With Hook',
    'Double Low-9 Quotation Mark',
    'Horizontal Ellipsis',
    'Dagger',
    'Double Dagger',
    'Modifier Letter Circumflex Accent',
    'Per Mille Sign',
    'Uppercase S With Caron',
    'Single Left-Pointing Angle Quotation Mark',
    'Latin Capital Ligature OE',
    null,
    'Uppercase Z With Caron',
    null,
    null,
    'Left Single Quotation Mark',
    'Right Single Quotation Mark',
    'Left Double Quotation Mark',
    'Right Double Quotation Mark',
    'Bullet',
    'En Dash',
    'Em Dash',
    'Small Tilde',
    'Trade Mark Sign',
    'Lowercase S With Caron',
    'Single Right-Pointing Angle Quotation Mark',
    'Latin Small Ligature OE',
    null,
    'Lowercase Z With Caron',
    'Uppercase Y With Diaeresis',
    'No-Break Space',
    'Inverted Exclamation Mark',
    'Cent Sign',
    'Pound Sign',
    'Currency Sign',
    'Yen Sign',
    'Broken Bar',
    'Section Sign',
    'Diaeresis',
    'Copyright Sign',
    'Feminine Ordinal Indicator',
    'Left-Pointing Double Angle Quotation Mark',
    'Not Sign',
    'Soft Hyphen',
    'Registered Sign',
    'Macron',
    'Degree Sign',
    'Plus-Minus Sign',
    'Superscript Two',
    'Superscript Three',
    'Acute Accent',
    'Micro Sign',
    'Pilcrow Sign',
    'Middle Dot',
    'Cedilla',
    'Superscript One',
    'Masculine Ordinal Indicator',
    'Right-Pointing Double Angle Quotation Mark',
    'Vulgar Fraction One Quarter',
    'Vulgar Fraction One Half',
    'Vulgar Fraction Three Quarters',
    'Inverted Question Mark',
    'Uppercase A With Grave',
    'Uppercase A With Acute',
    'Uppercase A With Circumflex',
    'Uppercase A With Tilde',
    'Uppercase A With Diaeresis',
    'Uppercase A With Ring Above',
    'Uppercase AE',
    'Uppercase C With Cedilla',
    'Uppercase E With Grave',
    'Uppercase E With Acute',
    'Uppercase E With Circumflex',
    'Uppercase E With Diaeresis',
    'Uppercase I With Grave',
    'Uppercase I With Acute',
    'Uppercase I With Circumflex',
    'Uppercase I With Diaeresis',
    'Uppercase Eth',
    'Uppercase N With Tilde',
    'Uppercase O With Grave',
    'Uppercase O With Acute',
    'Uppercase O With Circumflex',
    'Uppercase O With Tilde',
    'Uppercase O With Diaeresis',
    'Multiplication Sign',
    'Uppercase O With Stroke',
    'Uppercase U With Grave',
    'Uppercase U With Acute',
    'Uppercase U With Circumflex',
    'Uppercase U With Diaeresis',
    'Uppercase Y With Acute',
    'Uppercase Thorn',
    'Lowercase Sharp S',
    'Lowercase A With Grave',
    'Lowercase A With Acute',
    'Lowercase A With Circumflex',
    'Lowercase A With Tilde',
    'Lowercase A With Diaeresis',
    'Lowercase A With Ring Above',
    'Lowercase AE',
    'Lowercase C With Cedilla',
    'Lowercase E With Grave',
    'Lowercase E With Acute',
    'Lowercase E With Circumflex',
    'Lowercase E With Diaeresis',
    'Lowercase I With Grave',
    'Lowercase I With Acute',
    'Lowercase I With Circumflex',
    'Lowercase I With Diaeresis',
    'Lowercase Eth',
    'Lowercase N With Tilde',
    'Lowercase O With Grave',
    'Lowercase O With Acute',
    'Lowercase O With Circumflex',
    'Lowercase O With Tilde',
    'Lowercase O With Diaeresis',
    'Division Sign',
    'Lowercase O With Stroke',
    'Lowercase U With Grave',
    'Lowercase U With Acute',
    'Lowercase U With Circumflex',
    'Lowercase U With Diaeresis',
    'Lowercase Y With Acute',
    'Lowercase Thorn',
    'Lowercase Y With Diaeresis',
];
// console.log(iso8859_1.length);
// console.log(iso8859_1.length);
export default class FontTool {
    name = 'Font2';
}
//# sourceMappingURL=font_tool.js.map